Pass core ID to port lock macros
FreeRTOS/FreeRTOS-Kernel pull request #1212
Opened 2024-12-21 17:38 UTC by felixvanoost

Description
-----------
Passes the core ID as an argument to the SMP lock macros port{GET/RELEASE}_{TASK/ISR}_LOCK in tasks.c. Since the functions calling these macros in `tasks.c` in SMP mode already keep track of the core ID since #1206, it allows the port-specific spinlock function implementations to eliminate their calls to `portGET_CORE_ID()`. This reduces the number of unnecessary, and generally slow, accesses to a peripheral register. I have summarised the worst-case number of eliminated calls to `portGET_CORE_ID()`:

| Function | # of eliminated calls |
| -------- | ------------------- |
| `prvCheckForRunStateChange()` | 5 |
| `vTaskSwitchContext()` | 4 |
| `vTaskEnterCritical()` | 2 |
| `vTaskEnterCriticalFromISR()` | 1 |
| `vTaskExitCritical()` | 2 |
| `vTaskExitCriticalFromISR()` | 1 |

Test Steps
-----------
Timing analysis coming shortly.

Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
#1204

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-24 19:25 UTC, jasonpcarroll commented
Hi @felixvanoost - sorry for the late response. This looks great! I am going to ping someone with a bit more familiarity with SMP implementation to also take a look.

2024-12-25 10:22 UTC, chinglee-iot reviewed
I have verified this change with the unit test PR, and it works without issues. The PR can be found at https://github.com/FreeRTOS/FreeRTOS/pull/1319.

Please note that this change is not backward compatible. Since all TASK and ISR spinlock port macros need to be implemented recursively, it makes sense to add the xCoreID parameter to these macros.

We should proceed to update the following ports for the port macros change:

    portable/ThirdParty/Community-Supported-Ports/GCC/CORTEX_A53_64-bit_UltraScale_MPSoC/portmacro.h
    portable/ThirdParty/Community-Supported-Ports/GCC/RP2350_ARM_NTZ/non_secure/portmacro.h
    portable/ThirdParty/Community-Supported-Ports/GCC/RP2350_RISC-V/include/portmacro.h
    portable/ThirdParty/Partner-Supported-Ports/TI/CORTEX_A53_64-BIT_TI_AM64_SMP/portmacro.h

2024-12-25 10:22 UTC, chinglee-iot commented on portable/ThirdParty/xClang/XCOREAI/portmacro.h
> +        #define portRELEASE_TASK_LOCK( xCoreID )          ( (void)xCoreID, rtos_lock_release( 1 ) )
```suggestion
        #define portGET_ISR_LOCK( xCoreID )               do{ ( void )( xCoreID ); rtos_lock_acquire( 0 ) ); } while( 0 )
        #define portRELEASE_ISR_LOCK( xCoreID )           do{ ( void )( xCoreID ); rtos_lock_release( 0 ) ); } while( 0 )
        #define portGET_TASK_LOCK( xCoreID )              do{ ( void )( xCoreID ); rtos_lock_acquire( 1 ) ); } while( 0 )
        #define portRELEASE_TASK_LOCK( xCoreID )          do{ ( void )( xCoreID ); rtos_lock_release( 1 ) ); } while( 0 )

```

2024-12-25 10:27 UTC, chinglee-iot approved these changes

2024-12-25 23:06 UTC, felixvanoost commented
> I have verified this change with the unit test PR, and it works without issues. The PR can be found at [FreeRTOS/FreeRTOS#1319](https://github.com/FreeRTOS/FreeRTOS/pull/1319).
> 
> Please note that this change is not backward compatible. Since all TASK and ISR spinlock port macros need to be implemented recursively, it makes sense to add the xCoreID parameter to these macros.
> 
> We should proceed to update the following ports for the port macros change:
> 
> ```
> portable/ThirdParty/Community-Supported-Ports/GCC/CORTEX_A53_64-bit_UltraScale_MPSoC/portmacro.h
> portable/ThirdParty/Community-Supported-Ports/GCC/RP2350_ARM_NTZ/non_secure/portmacro.h
> portable/ThirdParty/Community-Supported-Ports/GCC/RP2350_RISC-V/include/portmacro.h
> portable/ThirdParty/Partner-Supported-Ports/TI/CORTEX_A53_64-BIT_TI_AM64_SMP/portmacro.h
> ```

@chinglee-iot I've created PRs in both repos with the corresponding changes. :)

2024-12-27 20:19 UTC, jasonpcarroll approved these changes

2024-12-27 20:20 UTC, jasonpcarroll requested changes
Sorry could you fix the CMock unit tests?

2024-12-30 06:45 UTC, aggarg approved these changes

2024-12-30 08:00 UTC, aggarg commented
> Sorry could you fix the CMock unit tests?

@chinglee-iot addressed unit tests in this PR - https://github.com/FreeRTOS/FreeRTOS/pull/1319.

2024-12-30 08:42 UTC, tony-josi-aws approved these changes

2024-12-30 08:58 UTC, merged

2024-12-30 09:12 UTC, aggarg commented
@felixvanoost Thank you for your contribution!