Code cleanup
FreeRTOS/FreeRTOS-Kernel pull request #288
Opened 2021-03-22 08:31 UTC by carlo-dev-git

Misc coding cleanup

Description
-----------
Misc coding cleanup and typo fixes.

Test Steps
-----------
No steps needed.

Related Issue
-----------
No related issue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-22 14:52 UTC, RichardBarry requested changes

2021-03-22 14:52 UTC, RichardBarry commented on portable/RVDS/ARM_CM4F/port.c
> +    ldmia r0 !, { r4 - r11, r14 }
"r4-r11" was correct, is specifies registers r4 to r11, not a subtraction.  Likewise for all similar edits.

2021-03-22 14:52 UTC, RichardBarry commented on portable/RVDS/ARM_CM4F/port.c
> +    vstmdbeq r0 !, { s16 - s31 }
Likewise "r0!" was correct, it specifies writing back to the register.  Likewise for all similar edits.

2021-03-22 18:02 UTC, aggarg submitted a review, later dismissed

2021-03-23 20:02 UTC, carlo-dev-git commented
@aggarg Could you help me? Some checks were not successful:
```
Checking file: portable/RVDS/ARM_CM4F/portmacro.h...FAIL
* We do NOT require that all files contain the FreeRTOS File Header (copyright + license).      *
* Include the required updates to the '*_checker.py' script in your PR to make the check pass.  *
```

2021-03-23 20:54 UTC, aggarg approved these changes

2021-03-23 22:10 UTC, aggarg commented
/bot run checks

2021-03-24 14:17 UTC, RichardBarry approved these changes

2021-04-07 21:19 UTC, merged