这是一个实用的排序,可以将任务列表以固定的顺序打印.
FreeRTOS/FreeRTOS-Kernel pull request #291
Opened 2021-03-24 04:01 UTC by BaY1251

以前打印的任务列表是乱序的,查看非常不方便

此更新实现,将任务列表以固定顺序打印,方便查看.以往的乱序打印查看及其不便
-----------

避免随机顺序打印,更利于调试.
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-28 17:40 UTC, RichardBarry commented
Translation: "The previously printed task list is out of order, which is very inconvenient to view

This update is implemented to print the task list in a fixed order for easy viewing. The past out-of-order printing and viewing are inconvenient
Avoid printing in random order, which is more conducive to debugging"

2021-05-24 20:56 UTC, n9wxu requested changes

2021-05-24 20:56 UTC, n9wxu commented on tasks.c
> +            for(i = 1; i <= uxArraySize; i++)
Please add conditional compiling to make this feature optional.  In a large system, this O^2 algorithm could start to take a non-trivial amount of time.

2021-06-30 21:40 UTC, yanjos-dev commented
I'm going to close this PR due to inactivity. Please reopen this PR if you are still interested in making this change.

2021-06-30 21:40 UTC, closed without merging