Revert Portable/CodeWarrior formatting
FreeRTOS/FreeRTOS-Kernel pull request #831
Opened 2023-10-10 23:26 UTC by Skptak

Description
-----------
Revert the formatting on CodeWarrior ports

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-23 09:38 UTC, chinglee-iot requested changes
Compared with commit before #768 
d6bccb1f4 | 2023-09-05 | Gaurav-Aggarwal-AWS | Fix heap address calculation issue (#781)

https://github.com/FreeRTOS/FreeRTOS-Kernel/compare/d6bccb1f4...Skptak:FreeRTOS-Kernel:fixCodeWarriorFormatting

* INDENT-OFF/ON comments are removed. Suggest we add them back.
* configTICK_TYPE_WIDTH_IN_BITS is wrongly reverted. We should add it back.

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V1/portmacro.h
> -/* *INDENT-ON* */
Suggest we add back the INDENT-OFF/ON comments.

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V1/portmacro.h
>  #endif
configTICK_TYPE_WIDTH_IN_BITS is also wrongly reverted. We should add it back.

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V1/portmacro.h
> -/* *INDENT-OFF* */
Same suggestion for the INDENT-OFF/ON

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V2/portmacro.h
> -/* *INDENT-OFF* */
Same suggestion for INDENT-OFF/ON

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V2/portmacro.h
> -#if ( configTICK_TYPE_WIDTH_IN_BITS == TICK_TYPE_WIDTH_16_BITS )
Same suggestion for configTICK_TYPE_WIDTH_IN_BITS.

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/ColdFire_V2/portmacro.h
> +}
INDENT-OFF/ON suggestion.

2023-11-23 09:38 UTC, chinglee-iot commented on portable/CodeWarrior/HCS12/portmacro.h
> +#if( configUSE_16_BIT_TICKS == 1 )
configTICK_TYPE_WIDTH_IN_BITS suggestion.

2023-12-06 07:46 UTC, chinglee-iot approved these changes

2023-12-07 16:15 UTC, aggarg approved these changes

2023-12-07 16:16 UTC, merged